---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hailtechno-service"
  labels:
    app: "hailtechno"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: "hailtechno"
  type: "ClusterIP"